### PR TITLE
Schema to data node

### LINKED ISSUE #47: yang-cbor RW terminology comments
1. The document should be clearer on its use of terminology around schema nodes.  Mostly the encoding related to YANG data nodes, not YANG schema nodes.  I've provided more information in the comments section.

2. I find this document (along with the SID draft), somewhat confusing in that it references YANG schema nodes, but in most cases, it probably
only cares about the subset of YAND schema nodes that represent itemsthat are present in data tree instantiation.  RFC 7950 calls such 'schema nodes' as 'data nodes'.  For example, 'choice', 'case', 'input' and 'output' exist as nodes in the YANG schema tree, but are not data nodes and don't appear as instantiated data nodes.

Where this causes problems are in the definitions of: 'child' - (e.g., 'case' cannot be a child of a 'container' only a child of a 'choice', and equivalently for the definition of 'parent'.  This definitions are not heavily used and could perhaps be removed?

Hence my suggestion to clarify the text are:
 - potentially import and use data node rather than schema node.  Note that data node, as defined in RFC 7950, is a subset of schema nodes, so you still need the text saying an instance of a data node.  Arguably, the RFC 7950 definition of a data node is somewhat confusing.
 - please check everywhere where 'schema node' or 'data node' turns up in the text to ensure that you are referencing instances of that schema node rather than the schema node itself.  E.g., the second paragraph in section 3 states 'where each child schema node is encoded ...', but this should be an instance of child schema node.
 - ensure that if you are referring to the parent or child of a 'schema node' that the logic skip out the schema nodes that don't get encoded in the data tree.  E.g., when calculating SIDs.

### PR DESCRIPTION
**Pull request by mcr**
close #47

### CODE REVIEW

**Comment by abierman** [comment]
The terms from RFC 7930 need to be used and referenced
https://datatracker.ietf.org/doc/html/rfc7950#section-3

schema node and data node are both correct terms.

The term schema node instance is not correct and data node should be used to replace that term.

**Comment by cabo** [comment]
Examples for instances based on schema node identifiers that are not data node identifiers are in section 4.5 and 4.6 of COMI:

https://core-wg.github.io/comi/draft-ietf-core-comi.html#name-event-stream

So we have to be a bit careful here.

**Comment by abierman** [comment]
You mean this example
```
FORMAT:
  GET <stream-resource> Observe(0)

  2.05 Content (Content-Format: application/yang-instances+cbor)
  CBOR array of CBOR map of instance-identifier, instance-value
```

IMO this should not be considered to conform to YANG CBOR encoding.
This draft seems to support A simple map pair containing a key and a data item.
In every case the "SID as CBOR" key is representing a data node (instance of a schema node).

There are cases where a SID is encoded in the data item (instance-identifier, identityref).
On a separate thread, these are encoded as an integer, representing the complete SID.
A SID within a data item is always the full SID, and not encoded with tag 47.

**Comment by cabo** [comment]
The text in Section 4.5 is not consistent, it uses `application/yang-tree+cbor` -- I don't know what that is.  But the example is an array of what looks like data node instances, except that the top level key is the schema node identifier for a notification.

**Comment by abierman** [comment]
application/yang-instances+cbor

I do not know about this media type.
The encoding in the YANG CBOR draft is for application/yang-data+cbor.
For this media type, all SID keys will represent YANG data nodes.

**Comment by mcr** [comment]
This effort is wrong, and will not be merged.

**Pull request closed without merging**
